DATA_BLOCK "conn_example"
{
  InstructionName := 'TCON_IP_v4';
  LibVersion := '1.0';
  S7_Optimized_Access := 'TRUE'
}
AUTHOR : SIMATIC
FAMILY : MC7Plus
NAME : TC_IP_v4
VERSION : 1.0
NON_RETAIN
TCON_IP_v4

BEGIN
   InterfaceId := 64;
   ID := 1;
   ActiveEstablished := true;
   RemoteAddress.ADDR[1] := 192;
   RemoteAddress.ADDR[2] := 168;
   RemoteAddress.ADDR[3] := 10;
   RemoteAddress.ADDR[4] := 12;
   RemotePort := 2000;
   LocalPort := 0;

END_DATA_BLOCK
